# -*- coding: utf-8 -*-

XHS_PLATFORM_NAME = 'xhs'
DOUYIN_PLATFORM_NAME = 'dy'
KUAISHOU_PLATFORM_NAME = 'ks'
BILIBILI_PLATFORM_NAME = 'bili'
WEIBO_PLATFORM_NAME = 'wb'
TIEBA_PLATFORM_NAME = 'tieba'

EXCEL_ACCOUNT_SAVE = 'xlsx'
MYSQL_ACCOUNT_SAVE = 'mysql'

